//! Raw FFI bindings — wpe-webkit-2.0, libwpe-1.0, wpebackend-fdo-1.0,
//! wayland-server (wl_shm_buffer pixel access).
//!
//! Generated by bindgen in `build.rs`; included verbatim here.
//!
//! # Safety
//!
//! Every call through these bindings is `unsafe`. Callers must uphold the
//! C-API invariants documented in the upstream headers:
//!   - `/usr/include/wpe-webkit-2.0/wpe/webkit.h`
//!   - `/usr/include/wpe-1.0/wpe/wpe.h`
//!   - `/usr/include/wpe-fdo-1.0/wpe/fdo.h`
//!   - `/usr/include/wayland-server-core.h`

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/wpe_bindings.rs"));
