[package]
name = "buffr-history"
description = "SQLite-backed history store for buffr."
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
rusqlite = { workspace = true, features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
chrono = { workspace = true, features = ["serde", "clock"] }
url = "2"
buffr-store = { workspace = true, features = ["chrono"] }
