[package]
name = "buffr-ui"
description = "Browser chrome, command palette, and hint overlay for buffr."
version = "0.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1"
tracing = "0.1"
buffr-modal.workspace = true
softbuffer = "0.4"
fontdb = { version = "0.23", default-features = false, features = ["fs", "memmap"] }
fontdue = "0.9"
