[package]
name = "buffr-webview2"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "WebView2 (Windows) backend for buffr-engine"
publish = false

[dependencies]
buffr-engine.workspace = true
thiserror.workspace = true
tracing.workspace = true
