[package]
name = "buffr-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
buffr-config = { path = "../crates/buffr-config" }
buffr-modal = { path = "../crates/buffr-modal" }
buffr-core = { path = "../crates/buffr-core" }
buffr-bookmarks = { path = "../crates/buffr-bookmarks" }
toml = "1.1"

[[bin]]
name = "fuzz_target_keybind"
path = "fuzz_targets/fuzz_target_keybind.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_keys"
path = "fuzz_targets/fuzz_target_keys.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_config_toml"
path = "fuzz_targets/fuzz_target_config_toml.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_console_sentinel"
path = "fuzz_targets/fuzz_target_console_sentinel.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_netscape_import"
path = "fuzz_targets/fuzz_target_netscape_import.rs"
test = false
doc = false
bench = false
