//! WebView2 STA worker: owns the Win32 message pump + WebView2 COM objects.
//!
//! # Threading model
//!
//! WebView2 objects are COM apartment-threaded (STA). `WebView2Engine` is
//! `Send + Sync` (required by `BrowserEngine`). Bridge pattern:
//!
//! ```text
//! WebView2Engine (any thread — Send + Sync)
//!   cmd_tx ──── Command ────▶  sta_thread (mpsc)
//!                                ├─ CoInitializeEx(COINIT_APARTMENTTHREADED)
//!                                ├─ GetAvailableCoreWebView2BrowserVersionString (probe)
//!                                ├─ CreateCoreWebView2EnvironmentWithOptions (async, wait_with_pump)
//!                                ├─ Win32 message pump (GetMessage / DispatchMessage)
//!                                ├─ 10 ms WM_TIMER tick ──▶ drain commands
//!                                └─ ICoreWebView2Controller + ICoreWebView2 per tab
//!   engine_state ────────────────────────────────▶ Arc<Mutex<EngineState>>
//!                (written by event delegates on STA thread; read from any thread)
//! ```
//!
//! # Controller path choice: HWND
//!
//! WebView2 supports two controller paths:
//!
//! - **Composition path** (`CreateCoreWebView2CompositionController` +
//!   `ICoreWebView2CompositionController` + `DesktopWindowTarget`) — preferred
//!   for full OSR pixel readback via D3D11 staging, but requires WinRT Visual
//!   Layer interop which is difficult to cross-compile to `x86_64-pc-windows-gnu`
//!   and outside Phase B scope.
//!
//! - **HWND path** (`CreateCoreWebView2Controller` on a hidden top-level
//!   window) — simpler, cross-compiles cleanly, supports `ICoreWebView2::Navigate`,
//!   all navigation events, and `ICoreWebView2::CapturePreview` for future OSR.
//!
//! **Phase B-2 uses the HWND path.** A hidden 1×1 `HWND` is created per-tab.
//! `ICoreWebView2Controller::SetIsVisible(false)` keeps it off-screen.
//!
//! TODO(phase-c): When the OSR pixel pipeline lands, consider switching the
//! active tab controller to composition mode or using `CapturePreview`.
//!
//! # Async bridge
//!
//! `CreateCoreWebView2EnvironmentWithOptions` and
//! `CreateCoreWebView2Controller` are asynchronous. The `webview2-com` crate
//! exposes `wait_with_pump` (a `GetMessage`/`DispatchMessage` loop that
//! `try_recv`s after each message) which is exactly the STA pattern needed.
//! Both async operations are bridged using the
//! `CreateCoreWebView2EnvironmentCompletedHandler::wait_for_async_operation`
//! and `CreateCoreWebView2ControllerCompletedHandler::wait_for_async_operation`
//! helpers generated by the `#[completed_callback]` macro.

use std::path::Path;
use std::sync::{Arc, Mutex, mpsc};
use std::thread;
use std::time::Duration;

use buffr_engine::{SharedOsrFrame, SharedOsrViewState, TabId, TabSummary};

use super::error::WebView2Error;
use super::input::WebView2InputEvent;
use super::osr::{paint_blank, request_capture};
use super::runtime::TabEntry;

// ── EngineState (thread-safe snapshot) ────────────────────────────────────────

/// Thread-safe tab snapshot. Updated by the STA thread; read from any thread.
pub(crate) struct EngineState {
    /// Open tabs in strip order.
    pub tabs: Vec<TabInfo>,
    /// Index of the active tab in `tabs`.
    pub active_idx: Option<usize>,
    /// Next tab id counter.
    pub next_id: u64,
    /// Current viewport width (pixels).
    pub width: u32,
    /// Current viewport height (pixels).
    pub height: u32,
}

impl EngineState {
    pub(crate) fn new(width: u32, height: u32) -> Self {
        EngineState {
            tabs: Vec::new(),
            active_idx: None,
            next_id: 1,
            width,
            height,
        }
    }

    pub(crate) fn next_tab_id(&mut self) -> TabId {
        let id = TabId(self.next_id);
        self.next_id += 1;
        id
    }

    pub(crate) fn summaries(&self) -> Vec<TabSummary> {
        self.tabs.iter().map(|t| t.to_summary()).collect()
    }
}

/// Shared in-flight flag for `CapturePreview` — prevents overlapping captures.
///
/// Cloned into the `CapturePreviewCompletedHandler` closure in `osr.rs` and
/// also held by `StaRuntime`. Both sides share the same `Arc<Mutex<bool>>`.
pub(crate) type CaptureInFlight = std::sync::Arc<std::sync::Mutex<bool>>;

/// Lightweight per-tab info mirrored from the STA thread.
#[derive(Clone)]
pub(crate) struct TabInfo {
    pub id: TabId,
    pub url: String,
    pub title: String,
    pub is_loading: bool,
    pub can_go_back: bool,
    pub can_go_forward: bool,
    pub progress: f64,
    /// Current zoom level. Updated from the STA thread after every
    /// `ICoreWebView2Controller::SetZoomFactor(...)` call; read by
    /// `active_zoom_level()` without blocking the STA thread.
    pub zoom: f64,
}

impl TabInfo {
    pub(crate) fn to_summary(&self) -> TabSummary {
        TabSummary {
            id: self.id,
            browser_id: 0,
            title: self.title.clone(),
            url: self.url.clone(),
            progress: self.progress as f32,
            is_loading: self.is_loading,
            pinned: false,
            private: false,
        }
    }
}

// ── Commands ──────────────────────────────────────────────────────────────────

#[allow(dead_code)]
pub(crate) enum Command {
    OpenTab {
        url: String,
        reply: mpsc::SyncSender<Result<TabId, WebView2Error>>,
    },
    CloseTab {
        id: TabId,
        reply: mpsc::SyncSender<Result<bool, WebView2Error>>,
    },
    SelectTab {
        id: TabId,
    },
    CycleTab {
        forward: bool,
    },
    Navigate {
        url: String,
        reply: mpsc::SyncSender<Result<(), WebView2Error>>,
    },
    GoBack,
    GoForward,
    Reload,
    Stop,
    /// Set the active tab's zoom level.
    ///
    /// On Windows: calls `ICoreWebView2Controller::SetZoomFactor(clamped)` and
    /// mirrors the clamped value into the shared `EngineState` so that
    /// `active_zoom_level()` reads it without round-tripping the STA thread.
    ///
    /// Source: webview2-com-sys-0.39.1/src/bindings.rs — `ICoreWebView2Controller`
    /// exposes `pub unsafe fn SetZoomFactor(&self, zoomfactor: f64)`.
    SetZoom(f64),
    Resize {
        width: u32,
        height: u32,
    },
    ForcePaint,
    /// Trigger a `CapturePreview` on the active tab's webview (fire-and-forget).
    ///
    /// Posted by the NavigationCompleted event handler after a page load finishes.
    /// The STA worker calls `request_capture` on the active tab if available and
    /// no capture is already in-flight.
    TriggerCapture,
    /// Dispatch an input event on the STA thread via `PostMessageW` (Option A).
    ///
    /// Fire-and-forget: no reply channel. Input events return `()` on the
    /// `BrowserEngine` trait surface.
    ///
    /// The STA worker calls `osr_dispatch_input`, which looks up the active
    /// tab's hidden HWND and posts the appropriate Win32 message
    /// (`WM_KEYDOWN`, `WM_MOUSEMOVE`, etc.) to WebView2's child WndProc.
    SendInput(WebView2InputEvent),
    QueryCanGoBack {
        reply: mpsc::SyncSender<bool>,
    },
    QueryCanGoForward {
        reply: mpsc::SyncSender<bool>,
    },
    Shutdown,
}

// ── WorkerHandle ──────────────────────────────────────────────────────────────

#[derive(Clone)]
pub(crate) struct WorkerHandle {
    tx: mpsc::SyncSender<Command>,
}

impl WorkerHandle {
    pub(crate) fn send(&self, cmd: Command) {
        let _ = self.tx.send(cmd);
    }

    pub(crate) fn call<T: Send + 'static>(
        &self,
        build: impl FnOnce(mpsc::SyncSender<T>) -> Command,
    ) -> Result<T, WebView2Error> {
        let (reply_tx, reply_rx) = mpsc::sync_channel(1);
        self.send(build(reply_tx));
        reply_rx
            .recv_timeout(Duration::from_secs(30))
            .map_err(|_| WebView2Error::WorkerTimeout)
    }
}

// ── STA runtime (lives on the STA worker thread) ─────────────────────────────

struct StaRuntime {
    tabs: Vec<TabEntry>,
    active_idx: Option<usize>,
    frame: SharedOsrFrame,
    view: SharedOsrViewState,
    engine_state: Arc<Mutex<EngineState>>,
    /// Sender half of the STA command channel. Passed into `TabEntry::new` so
    /// that event handlers (e.g. NavigationCompleted) can post `TriggerCapture`
    /// back to the STA worker loop.
    cmd_tx: mpsc::SyncSender<Command>,
    /// Shared WebView2 environment. Constructed once at worker startup via
    /// `CreateCoreWebView2EnvironmentWithOptions`.
    #[cfg(target_os = "windows")]
    environment: webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment,
    /// In-flight guard for `CapturePreview` — shared with the completion handler
    /// closure in `osr.rs`. `true` while a capture is pending; cleared by the
    /// completion handler regardless of success or failure.
    capture_in_flight: CaptureInFlight,
}

impl StaRuntime {
    fn active_tab(&self) -> Option<&TabEntry> {
        self.active_idx.and_then(|i| self.tabs.get(i))
    }

    #[allow(dead_code)]
    fn active_tab_mut(&mut self) -> Option<&mut TabEntry> {
        self.active_idx.and_then(|i| self.tabs.get_mut(i))
    }

    fn tab_index_by_id(&self, id: TabId) -> Option<usize> {
        self.tabs.iter().position(|t| t.id == id)
    }

    fn open_tab(&mut self, url: &str) -> Result<TabId, WebView2Error> {
        let id = {
            let mut st = self.engine_state.lock().unwrap();
            st.next_tab_id()
        };
        #[cfg(target_os = "windows")]
        let entry = TabEntry::new(id, url, &self.engine_state, &self.environment, &self.cmd_tx)?;
        #[cfg(not(target_os = "windows"))]
        let entry = TabEntry::new(id, url, &self.engine_state);
        self.tabs.push(entry);
        self.active_idx = Some(self.tabs.len() - 1);
        self.sync_active_idx();
        self.paint();
        Ok(id)
    }

    fn close_tab(&mut self, id: TabId) -> Result<bool, WebView2Error> {
        let idx = self
            .tab_index_by_id(id)
            .ok_or(WebView2Error::TabNotFound(id))?;
        self.tabs.remove(idx);
        if let Ok(mut st) = self.engine_state.lock() {
            st.tabs.retain(|t| t.id != id);
        }
        match self.active_idx {
            Some(a) if a == idx => {
                self.active_idx = if self.tabs.is_empty() {
                    None
                } else {
                    Some(idx.saturating_sub(1).min(self.tabs.len() - 1))
                };
            }
            Some(a) if a > idx => {
                self.active_idx = Some(a - 1);
            }
            _ => {}
        }
        self.sync_active_idx();
        self.paint();
        Ok(!self.tabs.is_empty())
    }

    fn select_tab(&mut self, id: TabId) {
        if let Some(idx) = self.tab_index_by_id(id) {
            self.active_idx = Some(idx);
            self.sync_active_idx();
            self.paint();
        }
    }

    fn cycle_tab(&mut self, forward: bool) {
        let n = self.tabs.len();
        if n == 0 {
            return;
        }
        let cur = self.active_idx.unwrap_or(0);
        self.active_idx = Some(if forward {
            (cur + 1) % n
        } else {
            cur.checked_sub(1).unwrap_or(n - 1)
        });
        self.sync_active_idx();
        self.paint();
    }

    fn navigate(&mut self, url: &str) -> Result<(), WebView2Error> {
        match self.active_idx {
            Some(idx) => self.tabs[idx].load_uri(url, &self.engine_state),
            None => Err(WebView2Error::InitFailed("no active tab".into())),
        }
    }

    fn go_back(&self) {
        if let Some(tab) = self.active_tab() {
            tab.go_back();
        }
    }

    fn go_forward(&self) {
        if let Some(tab) = self.active_tab() {
            tab.go_forward();
        }
    }

    fn reload(&self) {
        if let Some(tab) = self.active_tab() {
            tab.reload();
        }
    }

    fn stop(&self) {
        if let Some(tab) = self.active_tab() {
            tab.stop();
        }
    }

    fn set_zoom(&mut self, level: f64) {
        let clamped = level.clamp(0.25, 5.0);
        let Some(active_idx) = self.active_idx else {
            return;
        };
        let id = self.tabs[active_idx].id;

        // On Windows: call ICoreWebView2Controller::SetZoomFactor.
        // Source: webview2-com-sys-0.39.1/src/bindings.rs
        //   `pub unsafe fn SetZoomFactor(&self, zoomfactor: f64) -> windows_core::Result<()>`
        // The controller field is held directly on TabEntry.
        #[cfg(target_os = "windows")]
        {
            // SAFETY: SetZoomFactor is a COM method on a valid controller
            // pointer owned by the STA thread. The STA thread is the only
            // consumer of these COM objects.
            if let Err(e) = unsafe { self.tabs[active_idx].controller.SetZoomFactor(clamped) } {
                tracing::warn!("webview2: SetZoomFactor({clamped}) failed: {e}");
            }
        }

        // Mirror the clamped value into EngineState so active_zoom_level()
        // reads it without blocking the STA thread.
        if let Ok(mut guard) = self.engine_state.lock()
            && let Some(t) = guard.tabs.iter_mut().find(|t| t.id == id)
        {
            t.zoom = clamped;
        }
    }

    fn resize(&mut self, width: u32, height: u32) {
        {
            let mut st = self.engine_state.lock().unwrap();
            st.width = width;
            st.height = height;
        }
        use std::sync::atomic::Ordering;
        self.view.width.store(width, Ordering::Relaxed);
        self.view.height.store(height, Ordering::Relaxed);
        // Notify each tab's controller of the new bounds.
        for tab in &mut self.tabs {
            tab.on_resize(width, height);
        }
        self.paint();
    }

    fn paint(&self) {
        // On Windows: if there is an active tab with a ready webview, request
        // a CapturePreview screenshot. Fall back to paint_blank when no tab is
        // available or when running on a non-Windows host (stub path).
        #[cfg(target_os = "windows")]
        {
            if let Some(tab) = self.active_tab() {
                request_capture(
                    tab.webview(),
                    Arc::clone(&self.frame),
                    Arc::clone(&self.view),
                    Arc::clone(&self.capture_in_flight),
                );
                return;
            }
        }
        paint_blank(&self.frame, &self.view);
    }

    fn sync_active_idx(&self) {
        if let Ok(mut st) = self.engine_state.lock() {
            st.active_idx = self.active_idx;
        }
    }

    fn can_go_back(&self) -> bool {
        self.active_tab().map(|t| t.can_go_back()).unwrap_or(false)
    }

    fn can_go_forward(&self) -> bool {
        self.active_tab()
            .map(|t| t.can_go_forward())
            .unwrap_or(false)
    }
}

// ── Command handler ───────────────────────────────────────────────────────────

/// Handle one command on the STA thread. Returns `true` to request shutdown.
fn handle_command(cmd: Command, rt: &mut StaRuntime) -> bool {
    match cmd {
        Command::OpenTab { url, reply } => {
            let _ = reply.send(rt.open_tab(&url));
        }
        Command::CloseTab { id, reply } => {
            let _ = reply.send(rt.close_tab(id));
        }
        Command::SelectTab { id } => {
            rt.select_tab(id);
        }
        Command::CycleTab { forward } => {
            rt.cycle_tab(forward);
        }
        Command::Navigate { url, reply } => {
            let _ = reply.send(rt.navigate(&url));
        }
        Command::GoBack => {
            rt.go_back();
        }
        Command::GoForward => {
            rt.go_forward();
        }
        Command::Reload => {
            rt.reload();
        }
        Command::Stop => {
            rt.stop();
        }
        Command::SetZoom(level) => {
            rt.set_zoom(level);
        }
        Command::Resize { width, height } => {
            rt.resize(width, height);
        }
        Command::ForcePaint => {
            rt.paint();
        }
        Command::TriggerCapture => {
            rt.paint();
        }
        Command::SendInput(event) => {
            // Option A: PostMessageW to the tab's hidden HWND.
            // WebView2's child WndProc processes standard Win32 messages the same
            // way a real user would, so no composition controller migration is needed.
            #[cfg(target_os = "windows")]
            osr_dispatch_input(&event, rt);
            #[cfg(not(target_os = "windows"))]
            {
                // Stub path: log only (unreachable at runtime on non-Windows).
                match &event {
                    WebView2InputEvent::Key(ev) => {
                        tracing::debug!(
                            "webview2 worker: key event '{}' — stub path (no-op)",
                            ev.description
                        );
                    }
                    WebView2InputEvent::Mouse(ev) => {
                        tracing::debug!(
                            "webview2 worker: mouse event ({},{}) — stub path (no-op)",
                            ev.x,
                            ev.y
                        );
                    }
                    WebView2InputEvent::Ime(_) => {
                        tracing::debug!(
                            "webview2 worker: IME event — stub path (no-op on non-Windows)"
                        );
                    }
                }
            }
        }
        Command::QueryCanGoBack { reply } => {
            let result = rt.can_go_back();
            let _ = reply.send(result);
        }
        Command::QueryCanGoForward { reply } => {
            let result = rt.can_go_forward();
            let _ = reply.send(result);
        }
        Command::Shutdown => {
            tracing::info!("webview2 worker: shutdown requested");
            return true;
        }
    }
    false
}

// ── Windows-specific helpers ──────────────────────────────────────────────────

/// Probe the WebView2 runtime presence before allocating COM resources.
///
/// Calls `GetAvailableCoreWebView2BrowserVersionString(NULL, &mut ver)`.
/// If the DLL returns a non-null PWSTR the runtime is installed.
/// If the call fails or returns a null pointer the runtime is missing.
///
/// # Safety invariant
///
/// `GetAvailableCoreWebView2BrowserVersionString` reads only registry keys
/// and is safe to call before `CoInitializeEx` per the WebView2 loader docs.
#[cfg(target_os = "windows")]
fn probe_runtime() -> Result<String, WebView2Error> {
    use webview2_com::Microsoft::Web::WebView2::Win32::GetAvailableCoreWebView2BrowserVersionString;
    use windows::Win32::System::Com::CoTaskMemFree;

    let mut ver = windows::core::PWSTR::null();
    // SAFETY: FFI call to WebView2Loader.dll. `&mut ver` is a valid out-pointer.
    // The returned PWSTR is allocated with CoTaskMemAlloc; we free it after
    // converting to String.
    unsafe {
        GetAvailableCoreWebView2BrowserVersionString(windows::core::PCWSTR::null(), &mut ver)
            .map_err(|e| {
                WebView2Error::InitFailed(format!(
                    "WebView2 Runtime not installed — see https://microsoft.com/edge/webview2 (HRESULT {:#010x})",
                    e.code().0 as u32
                ))
            })?;
    }

    if ver.is_null() {
        return Err(WebView2Error::InitFailed(
            "WebView2 Runtime not installed — see https://microsoft.com/edge/webview2".into(),
        ));
    }

    // SAFETY: `ver` is a valid PWSTR allocated by the WebView2 loader.
    // We own it and must free it with CoTaskMemFree.
    let version = unsafe {
        let s = ver.to_string().unwrap_or_default();
        // SAFETY: `ver` was allocated with CoTaskMemAlloc by the loader.
        CoTaskMemFree(Some(ver.0.cast()));
        s
    };

    Ok(version)
}

/// Create a hidden 1×1 top-level window to serve as the HWND parent for
/// `CreateCoreWebView2Controller`.
///
/// `pub(super)` so `runtime.rs` (sibling module) can call it from `TabEntry::new`.
///
/// The HWND is invisible and never shown. Its sole purpose is satisfying the
/// controller's parent window requirement so we can use the simpler HWND path.
///
/// # Safety invariant
///
/// `RegisterClassExW` / `CreateWindowExW` are Win32 API calls. Both are safe
/// to call after `CoInitializeEx`. The returned `HWND` is valid for the
/// lifetime of the STA thread.
#[cfg(target_os = "windows")]
pub(super) fn create_hidden_hwnd() -> Result<windows::Win32::Foundation::HWND, WebView2Error> {
    use windows::Win32::Foundation::{HWND, LPARAM, LRESULT, WPARAM};
    use windows::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows::Win32::UI::WindowsAndMessaging::{
        CreateWindowExW, DefWindowProcW, RegisterClassExW, WINDOW_EX_STYLE, WNDCLASSEXW,
        WS_OVERLAPPEDWINDOW,
    };
    use windows::core::w;

    let class_name = w!("buffr_wv2_host");

    // Minimal `extern "system"` wrapper so we can pass DefWindowProcW as a
    // function pointer matching the `WNDPROC` type alias. The inline function
    // is transparent — it just forwards to DefWindowProcW.
    //
    // SAFETY: This is called by the Win32 message dispatch machinery. All
    // parameters come from the OS and are valid for the duration of the call.
    unsafe extern "system" fn wnd_proc(
        hwnd: HWND,
        msg: u32,
        wparam: WPARAM,
        lparam: LPARAM,
    ) -> LRESULT {
        unsafe { DefWindowProcW(hwnd, msg, wparam, lparam) }
    }

    let hinstance = unsafe {
        GetModuleHandleW(None)
            .map_err(|e| WebView2Error::InitFailed(format!("GetModuleHandleW: {e}")))?
    };

    let wc = WNDCLASSEXW {
        cbSize: std::mem::size_of::<WNDCLASSEXW>() as u32,
        lpfnWndProc: Some(wnd_proc),
        hInstance: hinstance.into(),
        lpszClassName: class_name,
        ..Default::default()
    };

    // RegisterClassExW may fail if already registered (second tab open in same
    // process) — that is fine; we ignore the error and proceed to CreateWindowExW.
    // SAFETY: `wc` is valid for the duration of this call.
    unsafe { RegisterClassExW(&wc) };

    // SAFETY: All parameters are valid. The created window is immediately hidden
    // (WS_OVERLAPPEDWINDOW without WS_VISIBLE). We never call ShowWindow on it.
    let hwnd = unsafe {
        CreateWindowExW(
            WINDOW_EX_STYLE::default(),
            class_name,
            w!("buffr-webview2-host"),
            WS_OVERLAPPEDWINDOW,
            0,
            0,
            1,
            1,
            None,
            None,
            Some(hinstance.into()),
            None,
        )
        .map_err(|e| WebView2Error::InitFailed(format!("CreateWindowExW: {e}")))?
    };

    Ok(hwnd)
}

/// Dispatch one `WebView2InputEvent` to the active tab's hidden HWND via
/// `PostMessageW` (Option A input dispatch).
///
/// # Keyboard
///
/// `SetFocus(hwnd)` is called before each key event so WebView2's child
/// WndProc honours the key. Without focus WebView2 may silently discard
/// `WM_KEYDOWN`/`WM_KEYUP` on hidden HWNDs.
///
/// lParam for `WM_KEYDOWN` / `WM_KEYUP`:
///
/// ```text
/// bits 31-30: transition / previous-key-state (0 for down, 0b11 for up)
/// bits 16-23: scan code (from `Wv2KeyEvent::scan_code`)
/// bits  0-15: repeat count (1)
/// ```
///
/// # Mouse
///
/// Coordinates are packed into lParam with the standard Win32
/// `MAKELPARAM(x, y)` formula: `(y as u32) << 16 | (x as u16 as u32)`.
///
/// `WM_MOUSEWHEEL` packs the WHEEL_DELTA (in units of 120 per notch) into
/// the high word of wParam: `((delta as u16 as u32) << 16)`.
///
/// `WM_MOUSELEAVE` carries no coordinates — wParam and lParam are zero.
///
/// # Safety
///
/// All `PostMessageW` calls are in `unsafe` blocks. The HWND is valid for
/// the lifetime of the `TabEntry` (verified by `StaRuntime::active_tab`).
/// `SetFocus` is called inside an `unsafe` block; it only changes keyboard
/// focus within the Win32 subsystem and does not violate memory safety.
#[cfg(target_os = "windows")]
fn osr_dispatch_input(event: &super::input::WebView2InputEvent, rt: &StaRuntime) {
    use super::input::{Wv2MouseButton, Wv2MouseKind};
    use windows::Win32::Foundation::{LPARAM, WPARAM};
    use windows::Win32::UI::Controls::WM_MOUSELEAVE;
    use windows::Win32::UI::Input::KeyboardAndMouse::SetFocus;
    use windows::Win32::UI::WindowsAndMessaging::{
        PostMessageW, WM_KEYDOWN, WM_KEYUP, WM_LBUTTONDOWN, WM_LBUTTONUP, WM_MBUTTONDOWN,
        WM_MBUTTONUP, WM_MOUSEMOVE, WM_MOUSEWHEEL, WM_RBUTTONDOWN, WM_RBUTTONUP,
    };

    let hwnd = match rt.active_tab() {
        Some(tab) => tab.hwnd(),
        None => {
            tracing::debug!("webview2 worker: SendInput — no active tab, dropping event");
            return;
        }
    };

    match event {
        super::input::WebView2InputEvent::Key(ev) => {
            // Give the hidden HWND keyboard focus so WebView2's WndProc
            // accepts the synthesised key messages.
            // SAFETY: SetFocus is a Win32 API that changes the focused HWND
            // on this thread's message queue. The HWND is valid (owned by TabEntry).
            let _ = unsafe { SetFocus(Some(hwnd)) };

            // Build lParam: repeat=1, scan code in bits 16-23, transition bits.
            let scan = (ev.scan_code as u32) << 16;
            let (msg, lp_flags) = if ev.flags & 0x0002 != 0 {
                // KEYEVENTF_KEYUP: set bits 31 (transition) + 30 (prev state)
                (WM_KEYUP, (0b11u32) << 30)
            } else {
                (WM_KEYDOWN, 0u32)
            };
            let lparam_val = scan | lp_flags | 1u32;

            // SAFETY: PostMessageW posts a message to the hidden HWND's queue.
            // HWND is valid; msg/wParam/lParam are valid Win32 key-message fields.
            let _ = unsafe {
                PostMessageW(
                    Some(hwnd),
                    msg,
                    WPARAM(ev.vk as usize),
                    LPARAM(lparam_val as isize),
                )
            };
            tracing::debug!(
                "webview2 worker: PostMessageW key {} vk={}",
                if msg == WM_KEYDOWN { "DOWN" } else { "UP" },
                ev.vk
            );
        }

        super::input::WebView2InputEvent::Ime(ev) => {
            // IME dispatch via WM_CHAR-per-character.
            //
            // Full WM_IME_* dispatch requires reading the composition string from
            // an IME-managed buffer after WM_IME_COMPOSITION, which is difficult
            // to orchestrate from Rust without a live ImmGetCompositionString call
            // on the same thread.  The WM_CHAR approach (used by AutoHotkey,
            // Playwright, and other Win32 automation tools) is simpler and
            // sufficient for most web input handlers.
            //
            // Phase D: implement WM_IME_STARTCOMPOSITION → WM_IME_COMPOSITION
            // (GCS_COMPSTR + GCS_CURSORPOS) → WM_IME_ENDCOMPOSITION for proper
            // preedit display in native form elements.
            use super::input::Wv2ImeEvent;
            use windows::Win32::Foundation::{LPARAM, WPARAM};
            use windows::Win32::UI::WindowsAndMessaging::{PostMessageW, WM_CHAR};

            let hwnd = match rt.active_tab() {
                Some(tab) => tab.hwnd(),
                None => {
                    tracing::debug!("webview2 worker: SendInput(Ime) — no active tab, dropping");
                    return;
                }
            };

            let post_chars = |text: &str| {
                for ch in text.chars() {
                    let code_point = ch as u32;
                    // SAFETY: WM_CHAR with a valid Unicode scalar value is always safe.
                    let _ = unsafe {
                        PostMessageW(Some(hwnd), WM_CHAR, WPARAM(code_point as usize), LPARAM(1))
                    };
                }
            };

            match ev {
                Wv2ImeEvent::Preedit { text, cursor } => {
                    // Simplified: send preedit characters as WM_CHAR sequence.
                    // This does not display an OS preedit window — it inserts
                    // the composition text directly.  Phase D: WM_IME_COMPOSITION.
                    tracing::debug!(
                        text = %text,
                        ?cursor,
                        "webview2 worker: ime_set_composition via WM_CHAR (simplified, Phase D deferred)"
                    );
                    post_chars(text);
                }
                Wv2ImeEvent::Commit { text } => {
                    tracing::debug!(text = %text, "webview2 worker: ime_commit via WM_CHAR");
                    post_chars(text);
                }
                Wv2ImeEvent::Cancel => {
                    // Send VK_ESCAPE (0x1B) as WM_CHAR to dismiss the composition.
                    tracing::debug!("webview2 worker: ime_cancel via WM_CHAR(VK_ESCAPE)");
                    const VK_ESCAPE: usize = 0x1B;
                    let _ =
                        unsafe { PostMessageW(Some(hwnd), WM_CHAR, WPARAM(VK_ESCAPE), LPARAM(1)) };
                }
            }
        }

        super::input::WebView2InputEvent::Mouse(ev) => {
            // Pack (x, y) into lParam: high word = y, low word = x.
            // Equivalent to Win32 MAKELPARAM(x, y).
            let lp = (((ev.y as u16) as u32) << 16) | ((ev.x as u16) as u32);
            let lparam = LPARAM(lp as isize);

            let (msg, wparam_val): (u32, usize) = match &ev.kind {
                Wv2MouseKind::Move => (WM_MOUSEMOVE, 0),
                Wv2MouseKind::ButtonDown(btn) => {
                    let m = match btn {
                        Wv2MouseButton::Left => WM_LBUTTONDOWN,
                        Wv2MouseButton::Right => WM_RBUTTONDOWN,
                        Wv2MouseButton::Middle => WM_MBUTTONDOWN,
                    };
                    (m, 0)
                }
                Wv2MouseKind::ButtonUp(btn) => {
                    let m = match btn {
                        Wv2MouseButton::Left => WM_LBUTTONUP,
                        Wv2MouseButton::Right => WM_RBUTTONUP,
                        Wv2MouseButton::Middle => WM_MBUTTONUP,
                    };
                    (m, 0)
                }
                Wv2MouseKind::Leave => (WM_MOUSELEAVE, 0),
                Wv2MouseKind::Wheel { delta } => {
                    // High word of wParam = WHEEL_DELTA (i16 cast to u16 preserves sign).
                    let wp = ((*delta as i16 as u16 as u32) << 16) as usize;
                    (WM_MOUSEWHEEL, wp)
                }
                Wv2MouseKind::HWheel { delta } => {
                    // WM_MOUSEHWHEEL = 0x020E; not in Win32_UI_WindowsAndMessaging
                    // as a named constant, so use the raw value.
                    const WM_MOUSEHWHEEL: u32 = 0x020E;
                    let wp = ((*delta as i16 as u16 as u32) << 16) as usize;
                    (WM_MOUSEHWHEEL, wp)
                }
            };

            // WM_MOUSELEAVE has no coordinates — override lparam to zero.
            let final_lp = if msg == WM_MOUSELEAVE {
                LPARAM(0)
            } else {
                lparam
            };

            // SAFETY: PostMessageW posts a message to the hidden HWND's queue.
            // HWND is valid; msg/wParam/lParam are valid Win32 mouse-message fields.
            let _ = unsafe { PostMessageW(Some(hwnd), msg, WPARAM(wparam_val), final_lp) };
            tracing::debug!(
                "webview2 worker: PostMessageW mouse msg=0x{:04X} ({},{})",
                msg,
                ev.x,
                ev.y
            );
        }
    }
}

/// Create the `ICoreWebView2Environment` on the STA thread.
///
/// Uses `wait_with_pump` to service the Win32 message queue while the WebView2
/// loader initialises asynchronously. This is the required pattern for STA
/// threads: `GetMessage`/`DispatchMessage` keeps the apartment alive until the
/// callback fires.
///
/// `data_dir` is the user-data folder passed to the options. If `None`,
/// WebView2 uses a default path under `%APPDATA%`.
#[cfg(target_os = "windows")]
fn create_environment(
    data_dir: Option<&Path>,
) -> Result<webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment, WebView2Error>
{
    use webview2_com::{
        CoreWebView2EnvironmentOptions, CreateCoreWebView2EnvironmentCompletedHandler,
        Microsoft::Web::WebView2::Win32::CreateCoreWebView2EnvironmentWithOptions,
    };
    use windows::Win32::Foundation::E_POINTER;

    let options: webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2EnvironmentOptions =
        CoreWebView2EnvironmentOptions::default().into();

    // Convert data_dir to a wide-string PCWSTR. We encode it into a Vec<u16>
    // with a NUL terminator and keep the Vec alive for the duration of the call.
    let data_dir_wide: Option<Vec<u16>> = data_dir.map(|p| {
        use std::os::windows::ffi::OsStrExt;
        let mut v: Vec<u16> = p.as_os_str().encode_wide().collect();
        v.push(0);
        v
    });

    let (tx, rx) = std::sync::mpsc::channel::<
        Result<
            webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment,
            windows::core::Error,
        >,
    >();

    CreateCoreWebView2EnvironmentCompletedHandler::wait_for_async_operation(
        Box::new(move |handler| {
            let user_data_pcwstr = match &data_dir_wide {
                Some(v) => windows::core::PCWSTR(v.as_ptr()),
                None => windows::core::PCWSTR::null(),
            };
            // SAFETY: CreateCoreWebView2EnvironmentWithOptions is a WebView2Loader
            // API. `user_data_pcwstr` points to a valid NUL-terminated wide
            // string on the stack that outlives this closure invocation.
            // `options` is a valid COM interface pointer.
            // `handler` is valid for the duration of the async operation.
            unsafe {
                CreateCoreWebView2EnvironmentWithOptions(
                    windows::core::PCWSTR::null(),
                    user_data_pcwstr,
                    &options,
                    &handler,
                )
                .map_err(webview2_com::Error::WindowsError)
            }
        }),
        Box::new(move |error_code, env| {
            error_code?;
            tx.send(env.ok_or_else(|| windows::core::Error::from(E_POINTER)))
                .expect("send environment over mpsc");
            Ok(())
        }),
    )
    .map_err(|e| WebView2Error::InitFailed(format!("CreateCoreWebView2Environment: {e}")))?;

    rx.recv()
        .map_err(|_| WebView2Error::InitFailed("environment channel closed".into()))?
        .map_err(|e| WebView2Error::ComError(e.code().0 as u32))
}

// ── Spawn ─────────────────────────────────────────────────────────────────────

pub(crate) fn spawn(
    initial_url: &str,
    _width: u32,
    _height: u32,
    frame: SharedOsrFrame,
    view: SharedOsrViewState,
    engine_state: Arc<Mutex<EngineState>>,
    data_dir: Option<std::path::PathBuf>,
) -> Result<WorkerHandle, WebView2Error> {
    let (tx, rx) = mpsc::sync_channel::<Command>(64);
    // Clone before the closure captures `tx` so the WorkerHandle can hold a
    // sender to the same channel.
    let tx_for_handle = tx.clone();
    let initial_url = initial_url.to_owned();

    // Report startup errors back to the calling thread via a oneshot.
    let (init_tx, init_rx) = mpsc::sync_channel::<Result<(), WebView2Error>>(1);

    thread::Builder::new()
        .name("buffr-webview2-sta".into())
        .spawn(move || {
            tracing::info!("webview2 worker: starting STA thread");

            // ── COM STA initialisation ────────────────────────────────────────
            //
            // SAFETY: CoInitializeEx must be called once per thread before any
            // COM/WebView2 calls. COINIT_APARTMENTTHREADED declares this thread
            // as an STA, which matches WebView2's apartment requirement.
            // CoUninitialize is called in the defer below on every exit path.
            #[cfg(target_os = "windows")]
            let _com_guard = {
                use windows::Win32::System::Com::{
                    COINIT_APARTMENTTHREADED, CoInitializeEx, CoUninitialize,
                };
                // SAFETY: first COM call on this thread. No COM objects exist yet.
                let hr = unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) };
                if let Err(e) = hr.ok() {
                    let _ = init_tx.send(Err(WebView2Error::InitFailed(format!(
                        "CoInitializeEx failed: {e}"
                    ))));
                    return;
                }
                tracing::debug!("webview2 worker: COM STA initialised");
                // Return a guard value whose Drop calls CoUninitialize.
                // We use a simple wrapper so the call is guaranteed even on
                // early return.
                struct ComGuard;
                impl Drop for ComGuard {
                    fn drop(&mut self) {
                        // SAFETY: paired with the CoInitializeEx above on the
                        // same thread. All COM objects must be released before
                        // this runs. The STA runtime (tabs) is dropped before
                        // the thread exits, so all COM refs are gone by here.
                        unsafe { CoUninitialize() };
                        tracing::debug!("webview2 worker: COM STA uninitialised");
                    }
                }
                ComGuard
            };

            // ── Runtime presence check ────────────────────────────────────────
            //
            // SAFETY: probe_runtime calls GetAvailableCoreWebView2BrowserVersionString
            // which only reads the registry. Safe after CoInitializeEx.
            #[cfg(target_os = "windows")]
            let runtime_version = match probe_runtime() {
                Ok(v) => v,
                Err(e) => {
                    let _ = init_tx.send(Err(e));
                    return;
                }
            };
            #[cfg(target_os = "windows")]
            tracing::info!("webview2 worker: runtime version = {runtime_version}");

            // ── Environment construction ──────────────────────────────────────
            //
            // Blocks on the STA message pump until the WebView2 loader callback
            // fires. This is the correct async-on-STA pattern.
            #[cfg(target_os = "windows")]
            let environment = match create_environment(data_dir.as_deref()) {
                Ok(env) => env,
                Err(e) => {
                    let _ = init_tx.send(Err(e));
                    return;
                }
            };
            #[cfg(target_os = "windows")]
            tracing::info!("webview2 worker: ICoreWebView2Environment ready");

            // Signal successful init to the spawning thread.
            let _ = init_tx.send(Ok(()));

            // ── Construct StaRuntime ──────────────────────────────────────────
            #[cfg(target_os = "windows")]
            let mut runtime = StaRuntime {
                tabs: Vec::new(),
                active_idx: None,
                frame: Arc::clone(&frame),
                view: Arc::clone(&view),
                engine_state: Arc::clone(&engine_state),
                cmd_tx: tx.clone(),
                environment,
                capture_in_flight: std::sync::Arc::new(std::sync::Mutex::new(false)),
            };

            #[cfg(not(target_os = "windows"))]
            let mut runtime = {
                // Non-Windows path never reaches here (spawn is only called via
                // the Windows platform path), but the compiler still type-checks
                // both branches.
                let _ = (frame, view, engine_state, data_dir);
                return;
            };

            // Open initial tab.
            if let Err(e) = runtime.open_tab(&initial_url) {
                tracing::error!("webview2 worker: failed to open initial tab: {e}");
            }

            tracing::info!("webview2 worker: entering message pump loop");

            // ── Message pump + command drain ──────────────────────────────────
            //
            // HWND path: we use a GetMessage/DispatchMessage pump so COM can
            // deliver WebView2 callbacks (navigation events, etc.) to the STA.
            // Commands are drained via try_recv inside the WM_TIMER handler.
            //
            // The timer fires every 10 ms so command latency is bounded.
            // GetMessage blocks until a message is available, keeping CPU at 0
            // while idle.
            //
            // TODO(#106-followup): once a DesktopWindowTarget / composition
            // controller is introduced, switch to PeekMessage + NtWaitFor if
            // lower latency is needed.
            #[cfg(target_os = "windows")]
            {
                use windows::Win32::UI::WindowsAndMessaging::{
                    DispatchMessageW, GetMessageW, KillTimer, MSG, PostQuitMessage, SetTimer,
                    TranslateMessage, WM_QUIT, WM_TIMER,
                };

                // WM_TIMER ID for 10 ms command-drain tick.
                const CMD_TIMER_ID: usize = 1;
                // WM_TIMER ID for 250 ms OSR CapturePreview tick.
                const OSR_TIMER_ID: usize = 2;

                // SAFETY: SetTimer with HWND(None) posts WM_TIMER to the
                // thread message queue. CMD_TIMER_ID fires every 10 ms to drain
                // the command channel. OSR_TIMER_ID fires every 250 ms (4 fps
                // steady tick) to trigger CapturePreview captures.
                unsafe { SetTimer(None, CMD_TIMER_ID, 10, None) };
                unsafe { SetTimer(None, OSR_TIMER_ID, 250, None) };

                let mut msg = MSG::default();
                'pump: loop {
                    // SAFETY: GetMessageW is a blocking Win32 call. `&mut msg`
                    // is a valid out-pointer. HWND(None) means "all messages for
                    // this thread".
                    let ret = unsafe { GetMessageW(&mut msg, None, 0, 0).0 };
                    match ret {
                        -1 => {
                            tracing::error!("webview2 worker: GetMessageW error");
                            break 'pump;
                        }
                        0 => {
                            tracing::info!("webview2 worker: WM_QUIT received");
                            break 'pump;
                        }
                        _ => {
                            if msg.message == WM_TIMER && msg.wParam.0 == CMD_TIMER_ID {
                                // Drain all pending commands.
                                loop {
                                    match rx.try_recv() {
                                        Ok(cmd) => {
                                            if handle_command(cmd, &mut runtime) {
                                                // SAFETY: PostQuitMessage is the
                                                // standard way to exit a Win32
                                                // message loop from within the loop.
                                                unsafe { PostQuitMessage(0) };
                                                break 'pump;
                                            }
                                        }
                                        Err(mpsc::TryRecvError::Empty) => break,
                                        Err(mpsc::TryRecvError::Disconnected) => {
                                            tracing::info!("webview2 worker: channel closed");
                                            unsafe { PostQuitMessage(0) };
                                            break 'pump;
                                        }
                                    }
                                }
                            } else if msg.message == WM_TIMER && msg.wParam.0 == OSR_TIMER_ID {
                                // 250 ms CapturePreview steady tick.
                                // `paint()` calls `request_capture` on the active
                                // tab if one is ready; in-flight flag prevents
                                // overlapping captures.
                                runtime.paint();
                            } else if msg.message == WM_QUIT {
                                break 'pump;
                            } else {
                                // SAFETY: Standard Win32 message dispatch. All
                                // messages not consumed above are forwarded.
                                unsafe {
                                    let _ = TranslateMessage(&msg);
                                    DispatchMessageW(&msg);
                                }
                            }
                        }
                    }
                }

                // SAFETY: KillTimer paired with SetTimer above.
                unsafe {
                    let _ = KillTimer(None, CMD_TIMER_ID);
                    let _ = KillTimer(None, OSR_TIMER_ID);
                };
            }

            tracing::info!("webview2 worker: exiting");
            // _com_guard Drop calls CoUninitialize here.
        })
        .map_err(|e| WebView2Error::InitFailed(e.to_string()))?;

    // Wait for the STA thread to finish COM + environment initialisation.
    // On failure the thread sends Err and exits early; we propagate that error.
    init_rx
        .recv_timeout(Duration::from_secs(30))
        .map_err(|_| WebView2Error::InitFailed("worker init timed out".into()))??;

    Ok(WorkerHandle { tx: tx_for_handle })
}
