//! WebView2 STA worker: owns the Win32 message pump + WebView2 COM objects.
//!
//! # Threading model
//!
//! WebView2 objects are COM apartment-threaded (STA). `WebView2Engine` is
//! `Send + Sync` (required by `BrowserEngine`). Bridge pattern:
//!
//! ```text
//! WebView2Engine (any thread — Send + Sync)
//!   cmd_tx ──── Command ────▶  sta_thread (mpsc)
//!                                ├─ CoInitializeEx(COINIT_APARTMENTTHREADED)
//!                                ├─ GetAvailableCoreWebView2BrowserVersionString (probe)
//!                                ├─ CreateCoreWebView2EnvironmentWithOptions (async, wait_with_pump)
//!                                ├─ Win32 message pump (GetMessage / DispatchMessage)
//!                                ├─ 10 ms WM_TIMER tick ──▶ drain commands
//!                                └─ ICoreWebView2Controller + ICoreWebView2 per tab
//!   engine_state ────────────────────────────────▶ Arc<Mutex<EngineState>>
//!                (written by event delegates on STA thread; read from any thread)
//! ```
//!
//! # Controller path choice: HWND
//!
//! WebView2 supports two controller paths:
//!
//! - **Composition path** (`CreateCoreWebView2CompositionController` +
//!   `ICoreWebView2CompositionController` + `DesktopWindowTarget`) — preferred
//!   for full OSR pixel readback via D3D11 staging, but requires WinRT Visual
//!   Layer interop which is difficult to cross-compile to `x86_64-pc-windows-gnu`
//!   and outside Phase B scope.
//!
//! - **HWND path** (`CreateCoreWebView2Controller` on a hidden top-level
//!   window) — simpler, cross-compiles cleanly, supports `ICoreWebView2::Navigate`,
//!   all navigation events, and `ICoreWebView2::CapturePreview` for future OSR.
//!
//! **Phase B-2 uses the HWND path.** A hidden 1×1 `HWND` is created per-tab.
//! `ICoreWebView2Controller::SetIsVisible(false)` keeps it off-screen.
//!
//! TODO(phase-c): When the OSR pixel pipeline lands, consider switching the
//! active tab controller to composition mode or using `CapturePreview`.
//!
//! # Async bridge
//!
//! `CreateCoreWebView2EnvironmentWithOptions` and
//! `CreateCoreWebView2Controller` are asynchronous. The `webview2-com` crate
//! exposes `wait_with_pump` (a `GetMessage`/`DispatchMessage` loop that
//! `try_recv`s after each message) which is exactly the STA pattern needed.
//! Both async operations are bridged using the
//! `CreateCoreWebView2EnvironmentCompletedHandler::wait_for_async_operation`
//! and `CreateCoreWebView2ControllerCompletedHandler::wait_for_async_operation`
//! helpers generated by the `#[completed_callback]` macro.

use std::path::Path;
use std::sync::{Arc, Mutex, mpsc};
use std::thread;
use std::time::Duration;

use buffr_engine::{SharedOsrFrame, SharedOsrViewState, TabId, TabSummary};

use super::error::WebView2Error;
use super::input::WebView2InputEvent;
use super::osr::paint_blank;
use super::runtime::TabEntry;

// ── EngineState (thread-safe snapshot) ────────────────────────────────────────

/// Thread-safe tab snapshot. Updated by the STA thread; read from any thread.
pub(crate) struct EngineState {
    /// Open tabs in strip order.
    pub tabs: Vec<TabInfo>,
    /// Index of the active tab in `tabs`.
    pub active_idx: Option<usize>,
    /// Next tab id counter.
    pub next_id: u64,
    /// Current viewport width (pixels).
    pub width: u32,
    /// Current viewport height (pixels).
    pub height: u32,
}

impl EngineState {
    pub(crate) fn new(width: u32, height: u32) -> Self {
        EngineState {
            tabs: Vec::new(),
            active_idx: None,
            next_id: 1,
            width,
            height,
        }
    }

    pub(crate) fn next_tab_id(&mut self) -> TabId {
        let id = TabId(self.next_id);
        self.next_id += 1;
        id
    }

    pub(crate) fn summaries(&self) -> Vec<TabSummary> {
        self.tabs.iter().map(|t| t.to_summary()).collect()
    }
}

/// Lightweight per-tab info mirrored from the STA thread.
#[derive(Clone)]
pub(crate) struct TabInfo {
    pub id: TabId,
    pub url: String,
    pub title: String,
    pub is_loading: bool,
    pub can_go_back: bool,
    pub can_go_forward: bool,
    pub progress: f64,
}

impl TabInfo {
    pub(crate) fn to_summary(&self) -> TabSummary {
        TabSummary {
            id: self.id,
            browser_id: 0,
            title: self.title.clone(),
            url: self.url.clone(),
            progress: self.progress as f32,
            is_loading: self.is_loading,
            pinned: false,
            private: false,
        }
    }
}

// ── Commands ──────────────────────────────────────────────────────────────────

#[allow(dead_code)]
pub(crate) enum Command {
    OpenTab {
        url: String,
        reply: mpsc::SyncSender<Result<TabId, WebView2Error>>,
    },
    CloseTab {
        id: TabId,
        reply: mpsc::SyncSender<Result<bool, WebView2Error>>,
    },
    SelectTab {
        id: TabId,
    },
    CycleTab {
        forward: bool,
    },
    Navigate {
        url: String,
        reply: mpsc::SyncSender<Result<(), WebView2Error>>,
    },
    GoBack,
    GoForward,
    Reload,
    Stop,
    Resize {
        width: u32,
        height: u32,
    },
    ForcePaint,
    /// Dispatch an input event on the STA thread.
    ///
    /// Fire-and-forget: no reply channel. Input events return `()` on the
    /// `BrowserEngine` trait surface.
    ///
    /// Phase B-2: STA has a controller but input synthesis (SendMouseInput /
    /// SendKeyboardInput) requires `ICoreWebView2CompositionController`, which
    /// is available only on the composition path. On the HWND path these remain
    /// no-op until a follow-up migrates to composition or uses SendInput.
    /// TODO(#106-followup): dispatch via ICoreWebView2CompositionController::SendMouseInput
    /// / SendKeyboardInput once the composition controller path is adopted.
    SendInput(WebView2InputEvent),
    QueryCanGoBack {
        reply: mpsc::SyncSender<bool>,
    },
    QueryCanGoForward {
        reply: mpsc::SyncSender<bool>,
    },
    Shutdown,
}

// ── WorkerHandle ──────────────────────────────────────────────────────────────

#[derive(Clone)]
pub(crate) struct WorkerHandle {
    tx: mpsc::SyncSender<Command>,
}

impl WorkerHandle {
    pub(crate) fn send(&self, cmd: Command) {
        let _ = self.tx.send(cmd);
    }

    pub(crate) fn call<T: Send + 'static>(
        &self,
        build: impl FnOnce(mpsc::SyncSender<T>) -> Command,
    ) -> Result<T, WebView2Error> {
        let (reply_tx, reply_rx) = mpsc::sync_channel(1);
        self.send(build(reply_tx));
        reply_rx
            .recv_timeout(Duration::from_secs(30))
            .map_err(|_| WebView2Error::WorkerTimeout)
    }
}

// ── STA runtime (lives on the STA worker thread) ─────────────────────────────

struct StaRuntime {
    tabs: Vec<TabEntry>,
    active_idx: Option<usize>,
    frame: SharedOsrFrame,
    view: SharedOsrViewState,
    engine_state: Arc<Mutex<EngineState>>,
    /// Shared WebView2 environment. Constructed once at worker startup via
    /// `CreateCoreWebView2EnvironmentWithOptions`.
    #[cfg(target_os = "windows")]
    environment: webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment,
}

impl StaRuntime {
    fn active_tab(&self) -> Option<&TabEntry> {
        self.active_idx.and_then(|i| self.tabs.get(i))
    }

    #[allow(dead_code)]
    fn active_tab_mut(&mut self) -> Option<&mut TabEntry> {
        self.active_idx.and_then(|i| self.tabs.get_mut(i))
    }

    fn tab_index_by_id(&self, id: TabId) -> Option<usize> {
        self.tabs.iter().position(|t| t.id == id)
    }

    fn open_tab(&mut self, url: &str) -> Result<TabId, WebView2Error> {
        let id = {
            let mut st = self.engine_state.lock().unwrap();
            st.next_tab_id()
        };
        #[cfg(target_os = "windows")]
        let entry = TabEntry::new(id, url, &self.engine_state, &self.environment)?;
        #[cfg(not(target_os = "windows"))]
        let entry = TabEntry::new(id, url, &self.engine_state);
        self.tabs.push(entry);
        self.active_idx = Some(self.tabs.len() - 1);
        self.sync_active_idx();
        self.paint();
        Ok(id)
    }

    fn close_tab(&mut self, id: TabId) -> Result<bool, WebView2Error> {
        let idx = self
            .tab_index_by_id(id)
            .ok_or(WebView2Error::TabNotFound(id))?;
        self.tabs.remove(idx);
        if let Ok(mut st) = self.engine_state.lock() {
            st.tabs.retain(|t| t.id != id);
        }
        match self.active_idx {
            Some(a) if a == idx => {
                self.active_idx = if self.tabs.is_empty() {
                    None
                } else {
                    Some(idx.saturating_sub(1).min(self.tabs.len() - 1))
                };
            }
            Some(a) if a > idx => {
                self.active_idx = Some(a - 1);
            }
            _ => {}
        }
        self.sync_active_idx();
        self.paint();
        Ok(!self.tabs.is_empty())
    }

    fn select_tab(&mut self, id: TabId) {
        if let Some(idx) = self.tab_index_by_id(id) {
            self.active_idx = Some(idx);
            self.sync_active_idx();
            self.paint();
        }
    }

    fn cycle_tab(&mut self, forward: bool) {
        let n = self.tabs.len();
        if n == 0 {
            return;
        }
        let cur = self.active_idx.unwrap_or(0);
        self.active_idx = Some(if forward {
            (cur + 1) % n
        } else {
            cur.checked_sub(1).unwrap_or(n - 1)
        });
        self.sync_active_idx();
        self.paint();
    }

    fn navigate(&mut self, url: &str) -> Result<(), WebView2Error> {
        match self.active_idx {
            Some(idx) => self.tabs[idx].load_uri(url, &self.engine_state),
            None => Err(WebView2Error::InitFailed("no active tab".into())),
        }
    }

    fn go_back(&self) {
        if let Some(tab) = self.active_tab() {
            tab.go_back();
        }
    }

    fn go_forward(&self) {
        if let Some(tab) = self.active_tab() {
            tab.go_forward();
        }
    }

    fn reload(&self) {
        if let Some(tab) = self.active_tab() {
            tab.reload();
        }
    }

    fn stop(&self) {
        if let Some(tab) = self.active_tab() {
            tab.stop();
        }
    }

    fn resize(&mut self, width: u32, height: u32) {
        {
            let mut st = self.engine_state.lock().unwrap();
            st.width = width;
            st.height = height;
        }
        use std::sync::atomic::Ordering;
        self.view.width.store(width, Ordering::Relaxed);
        self.view.height.store(height, Ordering::Relaxed);
        // Notify each tab's controller of the new bounds.
        for tab in &mut self.tabs {
            tab.on_resize(width, height);
        }
        self.paint();
    }

    fn paint(&self) {
        paint_blank(&self.frame, &self.view);
    }

    fn sync_active_idx(&self) {
        if let Ok(mut st) = self.engine_state.lock() {
            st.active_idx = self.active_idx;
        }
    }

    fn can_go_back(&self) -> bool {
        self.active_tab().map(|t| t.can_go_back()).unwrap_or(false)
    }

    fn can_go_forward(&self) -> bool {
        self.active_tab()
            .map(|t| t.can_go_forward())
            .unwrap_or(false)
    }
}

// ── Command handler ───────────────────────────────────────────────────────────

/// Handle one command on the STA thread. Returns `true` to request shutdown.
fn handle_command(cmd: Command, rt: &mut StaRuntime) -> bool {
    match cmd {
        Command::OpenTab { url, reply } => {
            let _ = reply.send(rt.open_tab(&url));
        }
        Command::CloseTab { id, reply } => {
            let _ = reply.send(rt.close_tab(id));
        }
        Command::SelectTab { id } => {
            rt.select_tab(id);
        }
        Command::CycleTab { forward } => {
            rt.cycle_tab(forward);
        }
        Command::Navigate { url, reply } => {
            let _ = reply.send(rt.navigate(&url));
        }
        Command::GoBack => {
            rt.go_back();
        }
        Command::GoForward => {
            rt.go_forward();
        }
        Command::Reload => {
            rt.reload();
        }
        Command::Stop => {
            rt.stop();
        }
        Command::Resize { width, height } => {
            rt.resize(width, height);
        }
        Command::ForcePaint => {
            rt.paint();
        }
        Command::SendInput(event) => {
            // TODO(#106-followup): dispatch via ICoreWebView2CompositionController::SendMouseInput
            // / SendKeyboardInput once the composition controller path is adopted.
            match &event {
                WebView2InputEvent::Key(ev) => {
                    tracing::debug!(
                        "webview2 worker: key event '{}' — input synthesis pending composition controller (#106-followup)",
                        ev.description
                    );
                }
                WebView2InputEvent::Mouse(ev) => {
                    tracing::debug!(
                        "webview2 worker: mouse event ({},{}) — input synthesis pending composition controller (#106-followup)",
                        ev.x,
                        ev.y
                    );
                }
            }
        }
        Command::QueryCanGoBack { reply } => {
            let result = rt.can_go_back();
            let _ = reply.send(result);
        }
        Command::QueryCanGoForward { reply } => {
            let result = rt.can_go_forward();
            let _ = reply.send(result);
        }
        Command::Shutdown => {
            tracing::info!("webview2 worker: shutdown requested");
            return true;
        }
    }
    false
}

// ── Windows-specific helpers ──────────────────────────────────────────────────

/// Probe the WebView2 runtime presence before allocating COM resources.
///
/// Calls `GetAvailableCoreWebView2BrowserVersionString(NULL, &mut ver)`.
/// If the DLL returns a non-null PWSTR the runtime is installed.
/// If the call fails or returns a null pointer the runtime is missing.
///
/// # Safety invariant
///
/// `GetAvailableCoreWebView2BrowserVersionString` reads only registry keys
/// and is safe to call before `CoInitializeEx` per the WebView2 loader docs.
#[cfg(target_os = "windows")]
fn probe_runtime() -> Result<String, WebView2Error> {
    use webview2_com::Microsoft::Web::WebView2::Win32::GetAvailableCoreWebView2BrowserVersionString;
    use windows::Win32::System::Com::CoTaskMemFree;

    let mut ver = windows::core::PWSTR::null();
    // SAFETY: FFI call to WebView2Loader.dll. `&mut ver` is a valid out-pointer.
    // The returned PWSTR is allocated with CoTaskMemAlloc; we free it after
    // converting to String.
    unsafe {
        GetAvailableCoreWebView2BrowserVersionString(windows::core::PCWSTR::null(), &mut ver)
            .map_err(|e| {
                WebView2Error::InitFailed(format!(
                    "WebView2 Runtime not installed — see https://microsoft.com/edge/webview2 (HRESULT {:#010x})",
                    e.code().0 as u32
                ))
            })?;
    }

    if ver.is_null() {
        return Err(WebView2Error::InitFailed(
            "WebView2 Runtime not installed — see https://microsoft.com/edge/webview2".into(),
        ));
    }

    // SAFETY: `ver` is a valid PWSTR allocated by the WebView2 loader.
    // We own it and must free it with CoTaskMemFree.
    let version = unsafe {
        let s = ver.to_string().unwrap_or_default();
        // SAFETY: `ver` was allocated with CoTaskMemAlloc by the loader.
        CoTaskMemFree(Some(ver.0.cast()));
        s
    };

    Ok(version)
}

/// Create a hidden 1×1 top-level window to serve as the HWND parent for
/// `CreateCoreWebView2Controller`.
///
/// `pub(super)` so `runtime.rs` (sibling module) can call it from `TabEntry::new`.
///
/// The HWND is invisible and never shown. Its sole purpose is satisfying the
/// controller's parent window requirement so we can use the simpler HWND path.
///
/// # Safety invariant
///
/// `RegisterClassExW` / `CreateWindowExW` are Win32 API calls. Both are safe
/// to call after `CoInitializeEx`. The returned `HWND` is valid for the
/// lifetime of the STA thread.
#[cfg(target_os = "windows")]
pub(super) fn create_hidden_hwnd() -> Result<windows::Win32::Foundation::HWND, WebView2Error> {
    use windows::Win32::Foundation::{HWND, LPARAM, LRESULT, WPARAM};
    use windows::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows::Win32::UI::WindowsAndMessaging::{
        CreateWindowExW, DefWindowProcW, RegisterClassExW, WINDOW_EX_STYLE, WNDCLASSEXW,
        WS_OVERLAPPEDWINDOW,
    };
    use windows::core::w;

    let class_name = w!("buffr_wv2_host");

    // Minimal `extern "system"` wrapper so we can pass DefWindowProcW as a
    // function pointer matching the `WNDPROC` type alias. The inline function
    // is transparent — it just forwards to DefWindowProcW.
    //
    // SAFETY: This is called by the Win32 message dispatch machinery. All
    // parameters come from the OS and are valid for the duration of the call.
    unsafe extern "system" fn wnd_proc(
        hwnd: HWND,
        msg: u32,
        wparam: WPARAM,
        lparam: LPARAM,
    ) -> LRESULT {
        unsafe { DefWindowProcW(hwnd, msg, wparam, lparam) }
    }

    let hinstance = unsafe {
        GetModuleHandleW(None)
            .map_err(|e| WebView2Error::InitFailed(format!("GetModuleHandleW: {e}")))?
    };

    let wc = WNDCLASSEXW {
        cbSize: std::mem::size_of::<WNDCLASSEXW>() as u32,
        lpfnWndProc: Some(wnd_proc),
        hInstance: hinstance.into(),
        lpszClassName: class_name,
        ..Default::default()
    };

    // RegisterClassExW may fail if already registered (second tab open in same
    // process) — that is fine; we ignore the error and proceed to CreateWindowExW.
    // SAFETY: `wc` is valid for the duration of this call.
    unsafe { RegisterClassExW(&wc) };

    // SAFETY: All parameters are valid. The created window is immediately hidden
    // (WS_OVERLAPPEDWINDOW without WS_VISIBLE). We never call ShowWindow on it.
    let hwnd = unsafe {
        CreateWindowExW(
            WINDOW_EX_STYLE::default(),
            class_name,
            w!("buffr-webview2-host"),
            WS_OVERLAPPEDWINDOW,
            0,
            0,
            1,
            1,
            None,
            None,
            Some(hinstance.into()),
            None,
        )
        .map_err(|e| WebView2Error::InitFailed(format!("CreateWindowExW: {e}")))?
    };

    Ok(hwnd)
}

/// Create the `ICoreWebView2Environment` on the STA thread.
///
/// Uses `wait_with_pump` to service the Win32 message queue while the WebView2
/// loader initialises asynchronously. This is the required pattern for STA
/// threads: `GetMessage`/`DispatchMessage` keeps the apartment alive until the
/// callback fires.
///
/// `data_dir` is the user-data folder passed to the options. If `None`,
/// WebView2 uses a default path under `%APPDATA%`.
#[cfg(target_os = "windows")]
fn create_environment(
    data_dir: Option<&Path>,
) -> Result<webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment, WebView2Error>
{
    use webview2_com::{
        CoreWebView2EnvironmentOptions, CreateCoreWebView2EnvironmentCompletedHandler,
        Microsoft::Web::WebView2::Win32::CreateCoreWebView2EnvironmentWithOptions,
    };
    use windows::Win32::Foundation::E_POINTER;

    let options: webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2EnvironmentOptions =
        CoreWebView2EnvironmentOptions::default().into();

    // Convert data_dir to a wide-string PCWSTR. We encode it into a Vec<u16>
    // with a NUL terminator and keep the Vec alive for the duration of the call.
    let data_dir_wide: Option<Vec<u16>> = data_dir.map(|p| {
        use std::os::windows::ffi::OsStrExt;
        let mut v: Vec<u16> = p.as_os_str().encode_wide().collect();
        v.push(0);
        v
    });

    let (tx, rx) = std::sync::mpsc::channel::<
        Result<
            webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment,
            windows::core::Error,
        >,
    >();

    CreateCoreWebView2EnvironmentCompletedHandler::wait_for_async_operation(
        Box::new(move |handler| {
            let user_data_pcwstr = match &data_dir_wide {
                Some(v) => windows::core::PCWSTR(v.as_ptr()),
                None => windows::core::PCWSTR::null(),
            };
            // SAFETY: CreateCoreWebView2EnvironmentWithOptions is a WebView2Loader
            // API. `user_data_pcwstr` points to a valid NUL-terminated wide
            // string on the stack that outlives this closure invocation.
            // `options` is a valid COM interface pointer.
            // `handler` is valid for the duration of the async operation.
            unsafe {
                CreateCoreWebView2EnvironmentWithOptions(
                    windows::core::PCWSTR::null(),
                    user_data_pcwstr,
                    &options,
                    &handler,
                )
                .map_err(webview2_com::Error::WindowsError)
            }
        }),
        Box::new(move |error_code, env| {
            error_code?;
            tx.send(env.ok_or_else(|| windows::core::Error::from(E_POINTER)))
                .expect("send environment over mpsc");
            Ok(())
        }),
    )
    .map_err(|e| WebView2Error::InitFailed(format!("CreateCoreWebView2Environment: {e}")))?;

    rx.recv()
        .map_err(|_| WebView2Error::InitFailed("environment channel closed".into()))?
        .map_err(|e| WebView2Error::ComError(e.code().0 as u32))
}

// ── Spawn ─────────────────────────────────────────────────────────────────────

pub(crate) fn spawn(
    initial_url: &str,
    _width: u32,
    _height: u32,
    frame: SharedOsrFrame,
    view: SharedOsrViewState,
    engine_state: Arc<Mutex<EngineState>>,
    data_dir: Option<std::path::PathBuf>,
) -> Result<WorkerHandle, WebView2Error> {
    let (tx, rx) = mpsc::sync_channel::<Command>(64);
    let initial_url = initial_url.to_owned();

    // Report startup errors back to the calling thread via a oneshot.
    let (init_tx, init_rx) = mpsc::sync_channel::<Result<(), WebView2Error>>(1);

    thread::Builder::new()
        .name("buffr-webview2-sta".into())
        .spawn(move || {
            tracing::info!("webview2 worker: starting STA thread");

            // ── COM STA initialisation ────────────────────────────────────────
            //
            // SAFETY: CoInitializeEx must be called once per thread before any
            // COM/WebView2 calls. COINIT_APARTMENTTHREADED declares this thread
            // as an STA, which matches WebView2's apartment requirement.
            // CoUninitialize is called in the defer below on every exit path.
            #[cfg(target_os = "windows")]
            let _com_guard = {
                use windows::Win32::System::Com::{
                    COINIT_APARTMENTTHREADED, CoInitializeEx, CoUninitialize,
                };
                // SAFETY: first COM call on this thread. No COM objects exist yet.
                let hr = unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) };
                if let Err(e) = hr.ok() {
                    let _ = init_tx.send(Err(WebView2Error::InitFailed(format!(
                        "CoInitializeEx failed: {e}"
                    ))));
                    return;
                }
                tracing::debug!("webview2 worker: COM STA initialised");
                // Return a guard value whose Drop calls CoUninitialize.
                // We use a simple wrapper so the call is guaranteed even on
                // early return.
                struct ComGuard;
                impl Drop for ComGuard {
                    fn drop(&mut self) {
                        // SAFETY: paired with the CoInitializeEx above on the
                        // same thread. All COM objects must be released before
                        // this runs. The STA runtime (tabs) is dropped before
                        // the thread exits, so all COM refs are gone by here.
                        unsafe { CoUninitialize() };
                        tracing::debug!("webview2 worker: COM STA uninitialised");
                    }
                }
                ComGuard
            };

            // ── Runtime presence check ────────────────────────────────────────
            //
            // SAFETY: probe_runtime calls GetAvailableCoreWebView2BrowserVersionString
            // which only reads the registry. Safe after CoInitializeEx.
            #[cfg(target_os = "windows")]
            let runtime_version = match probe_runtime() {
                Ok(v) => v,
                Err(e) => {
                    let _ = init_tx.send(Err(e));
                    return;
                }
            };
            #[cfg(target_os = "windows")]
            tracing::info!("webview2 worker: runtime version = {runtime_version}");

            // ── Environment construction ──────────────────────────────────────
            //
            // Blocks on the STA message pump until the WebView2 loader callback
            // fires. This is the correct async-on-STA pattern.
            #[cfg(target_os = "windows")]
            let environment = match create_environment(data_dir.as_deref()) {
                Ok(env) => env,
                Err(e) => {
                    let _ = init_tx.send(Err(e));
                    return;
                }
            };
            #[cfg(target_os = "windows")]
            tracing::info!("webview2 worker: ICoreWebView2Environment ready");

            // Signal successful init to the spawning thread.
            let _ = init_tx.send(Ok(()));

            // ── Construct StaRuntime ──────────────────────────────────────────
            #[cfg(target_os = "windows")]
            let mut runtime = StaRuntime {
                tabs: Vec::new(),
                active_idx: None,
                frame: Arc::clone(&frame),
                view: Arc::clone(&view),
                engine_state: Arc::clone(&engine_state),
                environment,
            };

            #[cfg(not(target_os = "windows"))]
            let mut runtime = {
                // Non-Windows path never reaches here (spawn is only called via
                // the Windows platform path), but the compiler still type-checks
                // both branches.
                let _ = (frame, view, engine_state, data_dir);
                return;
            };

            // Open initial tab.
            if let Err(e) = runtime.open_tab(&initial_url) {
                tracing::error!("webview2 worker: failed to open initial tab: {e}");
            }

            tracing::info!("webview2 worker: entering message pump loop");

            // ── Message pump + command drain ──────────────────────────────────
            //
            // HWND path: we use a GetMessage/DispatchMessage pump so COM can
            // deliver WebView2 callbacks (navigation events, etc.) to the STA.
            // Commands are drained via try_recv inside the WM_TIMER handler.
            //
            // The timer fires every 10 ms so command latency is bounded.
            // GetMessage blocks until a message is available, keeping CPU at 0
            // while idle.
            //
            // TODO(#106-followup): once a DesktopWindowTarget / composition
            // controller is introduced, switch to PeekMessage + NtWaitFor if
            // lower latency is needed.
            #[cfg(target_os = "windows")]
            {
                use windows::Win32::UI::WindowsAndMessaging::{
                    DispatchMessageW, GetMessageW, KillTimer, MSG, PostQuitMessage, SetTimer,
                    TranslateMessage, WM_QUIT, WM_TIMER,
                };

                // WM_TIMER ID used to trigger command draining.
                const CMD_TIMER_ID: usize = 1;
                // A synthetic HWND=None routes the timer message to the thread
                // queue rather than a window proc.
                // SAFETY: SetTimer with HWND(0) posts WM_TIMER to the thread
                // message queue. Interval is 10 ms.
                unsafe { SetTimer(None, CMD_TIMER_ID, 10, None) };

                let mut msg = MSG::default();
                'pump: loop {
                    // SAFETY: GetMessageW is a blocking Win32 call. `&mut msg`
                    // is a valid out-pointer. HWND(None) means "all messages for
                    // this thread".
                    let ret = unsafe { GetMessageW(&mut msg, None, 0, 0).0 };
                    match ret {
                        -1 => {
                            tracing::error!("webview2 worker: GetMessageW error");
                            break 'pump;
                        }
                        0 => {
                            tracing::info!("webview2 worker: WM_QUIT received");
                            break 'pump;
                        }
                        _ => {
                            if msg.message == WM_TIMER && msg.wParam.0 == CMD_TIMER_ID {
                                // Drain all pending commands.
                                loop {
                                    match rx.try_recv() {
                                        Ok(cmd) => {
                                            if handle_command(cmd, &mut runtime) {
                                                // SAFETY: PostQuitMessage is the
                                                // standard way to exit a Win32
                                                // message loop from within the loop.
                                                unsafe { PostQuitMessage(0) };
                                                break 'pump;
                                            }
                                        }
                                        Err(mpsc::TryRecvError::Empty) => break,
                                        Err(mpsc::TryRecvError::Disconnected) => {
                                            tracing::info!("webview2 worker: channel closed");
                                            unsafe { PostQuitMessage(0) };
                                            break 'pump;
                                        }
                                    }
                                }
                                // 250 ms blank-frame tick (every 25 timer iters).
                                // TODO(osr-capture): replace with CapturePreview.
                                runtime.paint();
                            } else if msg.message == WM_QUIT {
                                break 'pump;
                            } else {
                                // SAFETY: Standard Win32 message dispatch. All
                                // messages not consumed above are forwarded.
                                unsafe {
                                    let _ = TranslateMessage(&msg);
                                    DispatchMessageW(&msg);
                                }
                            }
                        }
                    }
                }

                // SAFETY: KillTimer paired with SetTimer above.
                // SAFETY: KillTimer paired with SetTimer above. Return value is
                // a success boolean; we ignore it as there's nothing to recover.
                unsafe {
                    let _ = KillTimer(None, CMD_TIMER_ID);
                };
            }

            tracing::info!("webview2 worker: exiting");
            // _com_guard Drop calls CoUninitialize here.
        })
        .map_err(|e| WebView2Error::InitFailed(e.to_string()))?;

    // Wait for the STA thread to finish COM + environment initialisation.
    // On failure the thread sends Err and exits early; we propagate that error.
    init_rx
        .recv_timeout(Duration::from_secs(30))
        .map_err(|_| WebView2Error::InitFailed("worker init timed out".into()))??;

    Ok(WorkerHandle { tx })
}
