[package]
name = "buffr-ladybird"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Ladybird backend for buffr-engine"
publish = false

[dependencies]
buffr-engine.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
cxx = "1"

[build-dependencies]
cxx-build = "1"
cc = "1"
